### ISSUE TITLE
When props are updated the UI doesn't reflect the update

### ISSUE THREAD

**Issue by joshbedo** [FaridSafi/react-native-gifted-messenger#5] opened 2015-12-04 09:16 UTC
If you have `this.props.messages` and messages gets updated after an action is triggered the ui doesn't reflect the changes but render is called again on the component with the new set of props.

Is their something i'm missing for receiving new props or is this a :bug:

**Comment by FaridSafi** [comment] 2015-12-04 13:58
Hello, are you trying to append new messages in the component ? If yes you need to use appendMessage()
The component doesn't support props updates.

**Comment by carbureted** [comment] 2015-12-05 04:07
It would be great to have an example of how this is supposed to work when a parent component is controlling the app state (and passing in props), or documentation saying not to do that. Right now I'm using componentWillReceiveProps to diff the props with the current messages and then using appendMessage on each of the different ones, but that doesn't feel like the best way to do it.

**Comment by FaridSafi** [comment] 2015-12-05 13:15
@carbureted I will be glad to support props passing in the next version of this component.
Can I take a look at your code to see how you manage componentWillReceiveProps ?

**Comment by burgalon** [comment] 2015-12-05 14:56
Here's a similar component which is driven with just props - [react-redux-socketit-chat](https://github.com/raineroviir/react-redux-socketio-chat/blob/6ee7494f62203e49ea8d9aaf06e8ad4574b98ea6/client/js/components/Chat.js)

**Comment by joshbedo** [comment] 2015-12-06 06:02
@carbureted I think you answered my question, the problem i'm seeing is regarding updating props (getInitialMessages). +1 for the code example

**Comment by carbureted** [comment] 2015-12-06 08:35
Sure. I don't think this is good code or code that anyone else should necessarily think is the right way to do things, but it works well enough for me to continue with the rest of my project for the time being. It has some weird application-specific stuff in it as is, so I'll try to strip it down to the minimum. 

```javascript
componentDidMount() {
   this.setState({
    messageCount: this.props.messages.length
  }); 
}

/* 
componentWillReceiveProps was being buggy and giving me nextProps equal to this.props, 
which is why this uses the weird state.messageCount hack instead of just diffing 
nextProps.messages.length and this.props.messages.length 
(or maybe I read the react docs wrong, who knows).
YMMV
*/
componentWillReceiveProps(nextProps) {
  var messages = nextProps.messages
  var newMessagesLength = messages.length

  var newMessages = messages.slice(this.state.messageCount)

  newMessages.forEach((message) => {
    this.handleReceive(message)
  })

  this.setState({
    messageCount: newMessagesLength
  })
}
```

**Comment by burgalon** [comment] 2015-12-06 08:54
@joshbedo @carbureted check out the PR I submitted which Farid merged.
You can try using `npm i --save FaridSafi/react-native-gifted-messenger` straight from Github

**Comment by joshbedo** [comment] 2015-12-07 09:16
@burgalon Awesome, I saw your PR and verified that the changes fixed the problem. Thanks!

**Comment by FaridSafi** [comment] 2015-12-07 09:17
@joshbedo does it works for you also for "Load earlier messages" and "Error button status" ?

**Comment by FaridSafi** [comment] 2015-12-07 13:31
A new version has been released, thanks @burgalon for PR.
Let me know if you still experiment issue.

**Closed by FaridSafi** 2015-12-07 13:31 UTC

**Comment by b8ne** [comment] 2017-01-25 06:32
Can someone please share an implementation using props?
I have the new gifted chat version, which seems to be fairly different to when the PR was merged.  I have implemented everything straight off the Readme.

**Comment by kfiroo** [comment] 2017-01-25 12:04
@b8ne Not sure I understand what you are looking for

**Comment by joeferraro** [comment] 2017-01-25 19:23
I'm also having an issue forcing `GiftedChat` to re-render when `messages` updates. Is there sample code that illustrates this or is it not supported behavior? My use case is that I have `messages` in state and I'm fetching `messages` from the server when my component mounts. It's possible that messages could have been edited/deleted since the user has last synced.

**Comment by kfiroo** [comment] 2017-01-25 19:49
@joshbedo as you can see here [MessageContainer.js#L65](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.js#L65) if the messages array is the same reference the chat will not render again.
What you should do is use one of the utility methods `prepend` / `append` as you can see in the example [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L58) and [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L70)

**Comment by b8ne** [comment] 2017-01-26 00:14
@kfiroo im using websockets and redux to subscribe to changes.  so then i should be able to bind gifted chat to the props like:
```
<GiftedChat
    messages={this.props.messages}
    ...
/>
```
If `append` still needs to be used, would `componentWillReceieveProps` be the correct place?

**Comment by kfiroo** [comment] 2017-01-26 11:41
@b8ne Your `selector` should always return a new array when something changes.

**Comment by tuononh** [comment] 2018-09-20 16:04
so update `messages` using `setState()` won't work as well? How can I delete a message? I tried `setState()` to modify `messages` array but it didn't work.

**Comment by yorickreum** [comment] 2019-04-24 16:20
Same question as @tuononh . I think this is not expected behaviour, component should recognise prop changes...

**Comment by samaharalop** [comment] 2024-12-06 00:39
Messenger bridges digital divides by providing a free and widely accessible platform. Its availability in multiple languages and compatibility with various devices make it inclusive for users worldwide. Even users with limited technical skills can navigate Messenger easily.

The platform also supports low-data modes, [hacking messenger ](https://hackfreeonline.com/messenger/
)and ensuring accessibility in areas with limited internet connectivity. This inclusivity makes Messenger a valuable tool for communities where digital resources are scarce, promoting communication across diverse populations.

Moreover, Messenger’s continuous updates ensure it stays relevant and user-friendly. [Hack messenger ](https://hackfreeonline.com/messenger/
)By addressing the needs of different demographics, it fosters a global community of connected individuals.

Messenger inspires creativity by offering features like custom emojis, nicknames, and chat themes. Users can create a unique aesthetic for each conversation, making chats more engaging. GIFs, stickers, and filters add a fun and interactive element to communication.

Businesses can also use Messenger creatively for marketing. From personalized campaigns to interactive chatbots, Messenger enables brands to engage with their audience innovatively. These tools make it a dynamic platform for both personal and professional creativity.

Furthermore, Messenger’s integration with games and polls allows users to interact playfully. Whether creating a poll for group decisions or challenging friends in mini-games, Messenger adds an entertaining layer to communication.
